sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NGxhl2DQ2xLe5ZIL5To1U2TePdcH5TcQ6oygKbcKfwrD/toU42hZaNVJQ26A/1ZUJD8BwHDAygeQ5fl9VyveqTzf7a/bwSMs/l5VAwL6JlLY24KODCwgLzh31cK8YXJFiyoUDCbkoBkNeT3hD/PhlNQP+9Grz+yq7N5ICVNplZUNbfp1AZ3Sjzxbm4H7dpTF8wr1rxK/U9hr4D1O7KrscWUBYp8h80t7C2Ru2r+3Sj+gtJZ5nmjyjax3Ed0wkHW/Y2IZy3dzgpLTsJFSReegRGxr7aicT3CsvYVtcVzgxTvxKaWTsJw43jqO8tKS3aqdrFe0ia9IDr7QTGbw6Gqxlgon2RJNzqc2nuXQ6nTil95enE3YWclZ4d8dOTVdF4AEm6RYPJx4HPouBIPqr7DjIzCMNYHeofltCOWi+GdWOykwW1HynTAfSKyhwqDr2oG3THFpo3QjX8Nciyq9nJgC8OWCOTG2/imJM38mHPd122O1jgPTT+5SMYhDrz3ym5lFq7y7rIVymF2HXB7iC5/UD1SVGjcvxN7fj5lYuYO0xknW8WaqPKKwd21ov1D7zkXfvrdicuPccM45OccxsAA7RSsClKW1HN/d3My8qP3qmPLlI9y4aOvPk6t1vWw1X4YgLiWj5ebQQDSCJCybrgmLmB41UF8WNLrlI8KK6XYH22g=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Backlog-Studies_3134
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy